# Generated by Django 3.2.16 on 2022-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-create_date',)},
        ),
        migrations.AddField(
            model_name='postgallery',
            name='image_alt_name',
            field=models.CharField(default='no-photo', max_length=200),
            preserve_default=False,
        ),
    ]
